# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/**/*"
    - "!src/{img,js,scss,pug}{,/**/*}"
  # Paths to Pug entry point
  pug:
    - "src/pug/pages/**/!(_)*.pug"
  # Paths to Sass entry point
  sass:
    - "src/scss/app.scss"
  # Paths to Sass libraries, which can then be loaded with @import
  sasslibs:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry point for webpack to bundle modules
  js:
    - "src/js/app.js"
  # Paths to Images for some optimization
  images:
    - "src/assets/img/**/*"
  